apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- manager.yaml

# These values are overridden with:
#   `make build-deployer RELATED_IMAGE_HYPERFLEET_API=.. RELATED_IMAGE_HYPERFLEET_OPERATOR=...`
# Or images can be set overridden here by modifying the image values
patches:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: RELATED_IMAGE_HYPERFLEET_API
        value: ${RELATED_IMAGE_HYPERFLEET_API}
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: RELATED_IMAGE_HYPERFLEET_OPERATOR
        value: ${RELATED_IMAGE_HYPERFLEET_OPERATOR}
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: ${RELATED_IMAGE_HYPERFLEET_OPERATOR}
  target:
    kind: Deployment
    name: controller-manager
